const path = require("path");
module.exports = {
    mode:"development",
    entry:{
        index:"./src/index.js",
        product:"./src/product.js"
    },
    output:{
        path:path.resolve(__dirname,"../dist"),
        filename:'[name].[hash].js'
    },
    module:{
        rules:[
            {
                test:/\.css$/,
                use:[
                    {loader:"style-loader"},
                    {loader:"css-loader"}
                ]
            },
            {
                test:/\.less$/,
                use:[
                    {loader:'style-loader'},
                    {loader:'css-loader'},
                    {loader:'less-loader'}
                ]
            },
            {
                test:/\.(jpg|png)$/,
                use:[
                    {loader:"url-loader"}
                ]
            },
            {
                test:/\.js$/,
                exclude:/(node_modules|bower_components)/,
                use:{
                    loader:'babel-loader',
                    options:{
                        presets:['env']
                    }
                }                
            },
            {
                test:/\.scss$/,
                use:[
                    {loader:'style-loader'},
                    {loader:'css-loader'},
                    {loader:'sass-loader'}
                ]
            }
        ]
    }
}